### ISSUE TITLE
[Question] "--ignore-files" does not work?

### ISSUE THREAD

**Issue by Yerik17170** [wrike/dart-code-metrics#143]
**What do you want to discuss?**
When I use the command line tool, "--ignore-files" does not seem to work. And only the absolute path can be used, the path "/**.dart" cannot be found. 
1. 
![image](https://user-images.githubusercontent.com/34933160/95726479-92658600-0cab-11eb-854a-d9d6e8004cd9.png)
2. 
![image](https://user-images.githubusercontent.com/34933160/95726636-c345bb00-0cab-11eb-9a80-d40de46475dd.png)

**Comment by dkrutskikh** [comment]
@Yerik17170 please try to run `metrics ./viola_sdk/vendor/ --cyclomatic-complexity=5 --ignore-files="{viola_sdk/vendor/widget/VAPageWidget.dart,viola_sdk/vendor/utils/VAHttpRequestUtil.dart}"`
