### ISSUE TITLE
Promoting

### ISSUE THREAD

**Issue by amorenew** [wrike/dart-code-metrics#145]
It is an awesome tool
I didn't know it is there before so I wonder if you could promote it on the dart linter team or make pull requests to merge it to the main tool?
https://github.com/dart-lang/linter/issues/2302

**Comment by incendial** [comment]
@amorenew Hi! Thank you for creating the issue, we are working on promotion for the package right now, but it's not connected with dart `linter` package. But your idea for making a list of popular plugins is great (it may also help others to develop new plugins).
As for merging into the main tool - this tools also has anti-patterns check which we want to develop and our approach with rules is a bit different (we support user configuration for each rule). So for now it seems that this package as a separate plugin is a good decision.

**Comment by amorenew** [comment]
Cool, I will close it for now till you got time to promote it.
