### ISSUE TITLE
How are you using this with codeclimate?

### ISSUE THREAD

**Issue by zgosalvez** [wrike/dart-code-metrics#175]
**What do you want to discuss?**

@dkrutskikh, I noticed that you recently updated the reporter. I want to integrate this with the Code Climate Engine but the Code Climate CLI is throwing an exception when using the codeclimate reporter. You can see the exact error in my PR draft here wrike/codeclimate-dart/pull/2 and from my fork here zgosalvez/codeclimate-dart/pull/1.

**Comment by dkrutskikh** [comment]
@zgosalvez I was publish 2.3.2 version with codeclimate report fixes

**Comment by zgosalvez** [comment]
Thanks @dkrutskikh
