### ISSUE TITLE
Exit code for CI

### ISSUE THREAD

**Issue by neokree** [wrike/dart-code-metrics#18]
Hello, 

It could be very useful to add an option like `--set-exit-on-alarm` and `--set-exit-on-warning` to allow this library to make a pipeline fail.

I'm talking about GitLab here, but I think that exit code are used in other CI tools to made them fail.

**Comment by Anrock** [comment]
Thanks for suggestion @neokree, we'll try to implement in near future.

**Comment by Anrock** [comment]
@neokree Hi, check out `--set-exit-on-violation-level` parameter in new 1.4.0 version

**Comment by neokree** [comment]
@Anrock Thank you!
