### ISSUE TITLE
[BUG] Provide documentation for how to use auto fixes

### ISSUE THREAD

**Issue by bbugh** [wrike/dart-code-metrics#195]
**What do you want to discuss?**

Hi! 👋 Thank you for the wonderful additions to the analyzer, some of these are so useful! Much appreciated.

Many of the rules suggest that they support auto fixes, but there's nothing in the documentation about how to use them. 

As far as I can tell, [dartanalyzer doesn't support auto fix](https://github.com/dart-lang/sdk/issues/33358) which is a couple of years old but I can't find anything new. I am able to apply the comma fix as a Quick Fix in VSCode, but I'd love if it happened automatically. I'm especially interested in the `prefer-trailing-comma` automatically running because `dartfmt` formatting without trailing commas is making me cray.

Thank you for reading.

**Comment by incendial** [comment]
@bbugh hi, thank you very much for the feedback, it's great to hear that!

As for auto fixes, currently they are supported only in a IDE context menu. We will add some 

Apparently dart now has `dart fix` command which is not listed [in the commands docs](https://github.com/dart-lang/sdk/tree/b0efb3738f9f5e34441fc43979c4401ff11a1eea/pkg/dartdev). I've made a little research and it seems that it covers a subset [of analyzer rules](https://github.com/dart-lang/sdk/blob/87cb3ede9e76dd503eb3cd4137e5aa1ca126c773/pkg/analysis_server/lib/src/services/linter/lint_names.dart) that is hardcode (sad and strange). So there is no way for us to easily support command line auto fixes.

Could u please elaborate more on 
>I'd love if it happened automatically 
Are u talking about some CLI command? Will it be ok if that will be a separate command and not `dart fix`, ex. `metrics fix` (as i said above it's not possible for now to extend this command rules list with external rules)?

**Comment by bbugh** [comment]
Thanks for the reply! Command line would be useful for pre-commit hooks and CI, but in this case auto fix in the editor (VS Code) would be a big enough win I think.

**Comment by bbugh** [comment]
Auto fix when auto format is on when saving, that is!

**Comment by incendial** [comment]
Unfortunately, i don't see a way to do that with the API that we use, which is provided by the dart analysis server (which is then used by VS Code extension).
I think that the most automatic way that we can implement without a huge amount of work is to add fix command to CLI.

**Comment by bbugh** [comment]
Got it, thanks for explaining. The dart tooling has some oddities for sure!

I think it would be helpful to add to the documentation the way to use the auto fixes. I have it installed as a dev dependency and the warnings showed up but I could my find a way to do any fixing, command line or editor.
