### ISSUE TITLE
Improve no-magic-number rule

### ISSUE THREAD

**Issue by Anrock** [wrike/dart-code-metrics#69]
Some field cases with false-positivish warnings:
```dart
final someDay = DateTime(2006, 12, 1); // DateTime has no const constructor, so there is always a warning or each int should be defined as const separately
```
```dart
Future.delayed(const Duration(seconds: 5)); // Triggered despite const constructor.
...
const delay = Duration(seconds: 5));
Future.delayed(delay); // This is fine. Not sure if should be fixed
```
```dart
... Intl.message(..., example: const <String, int>{ 'Assigneed': 3 } // Warning
```

So far it looks like rule should be altered to not trigger if magic number is inside const constructors and number literals in other const literals.
`DateTime` should be made an exception, since it doesn't have a const constructor and putting every argument in separate const declaration is inconvenient.

**Comment by csepanda** [comment]
I would like to append list of false-positive warning:
```
final foo = someIntValue / 2;
final bar = someIntValue / 3;
final snafu = someIntValue / 4;
```

Furthermore, it would be nice to have avoid running of this rule in the test directory.

**Comment by Anrock** [comment]
@csepanda #89 allows to configure allowed literals and disabling rules per-directory should be handled in #68
