### ISSUE TITLE
[New rule] Component annotation arguments ordering

### ISSUE THREAD

**Issue by incendial** [wrike/dart-code-metrics#92]
**Please describe what the rule should do:**
Enforces ordering for `@Component` Angular annotation arguments. Order should be configurable.
Available options:
* selector
* template(includes templateUrl and template)
* directives (includes directives and directiveTypes)
* pipes
* encapsulation
* styles (includes styles and styleUrls)
* exports (includes exports and exportAs)
* changeDetection
* visibility
* providers (includes providers and viewProviders)

**What category of rule is this? (place an "X" next to just one item)**

[ ] Warns about a potential error (problem)
[ ] Suggests an alternate way of doing something (suggestion)
[x] Other (please specify: enforces specific order)

**Provide 2-3 code examples that this rule will warn about (it will be better if you can provide both good and bad examples):**
With given config:
```yaml
- selector
- providers
- change-detection
```

Bad:
```dart
@Component(
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'component-selector',
)
```

Good:
```dart
@Component(
  selector: 'component-selector',
  changeDetection: ChangeDetectionStrategy.OnPush,
)
```

**Are you willing to submit a pull request to implement this rule?**
Yes

**Comment by incendial** [comment]
@Anrock @dkrutskikh what do you think? Do we need this?

**Comment by dkrutskikh** [comment]
@incendial I think yes! Great idea.

**Comment by Anrock** [comment]
Not sure, but why not. Some ppl may find it useful.
