### ISSUE TITLE
[Question] Line of codes are not equal to the file's line of code?

### ISSUE THREAD

**Issue by devforey** [wrike/dart-code-metrics#99]
**What do you want to discuss?**
I'm trying to know why the line of code reported by the tool isn't exactly the line of code of the file itself. I assume this is intended but I just need to know the reason behind and how the tool does it technically.

![image](https://user-images.githubusercontent.com/18719783/89512877-6ab6f500-d806-11ea-8777-0f88559dc776.png)
Line of code reported by the tool: **18**
Line of code inside the file: **37**

**Comment by Anrock** [comment]
@devforey what's the name of a rule triggered on these lines? Could you also copypaste code from screenshot as text here (or pastebin)?

**Comment by devforey** [comment]
Thanks for the reply! I checked if there are rules being triggered but there weren't rules being triggered for this file. 

I just run the code `metrics lib --reporter=html` then opened the HTML for the file.

**Comment by devforey** [comment]
I'm guessing the `Lines of code` in the reports are the number of lines inside the methods. I also see that it doesn't count empty lines.

It was just confusing. I expected the `Lines of code` in the reports are the file's lines of code.

**Comment by Anrock** [comment]
Probably we should rename to something like "executable lines of code" or something like that 🤔 @dkrutskikh what do you think?

**Comment by dkrutskikh** [comment]
@devforey thanks for highlight this problem, at this moment we collect information about executable lines of code
